/**
 * Page Registry
 * 
 * Central registry of all pages in the application.
 * Auto-generated by UR-DEV AI builder.
 */

export const pages = {
  '/': 'public/index.html'
};

export const getPagePath = (route: string): string | null => {
  return pages[route] || null;
};

export const getAllRoutes = (): string[] => {
  return Object.keys(pages);
};
