import React, { useEffect, useState, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Mail, Github, Settings, LogOut, User, HelpCircle, Sun, Users, CreditCard, Briefcase, Bell, ListTodo, Plug } from "lucide-react";
import { User as SupabaseUser } from "@supabase/supabase-js";
import { PlanWizard, PlanData } from "@/components/PlanWizard";
import { ProjectsDropdown, Project } from "@/components/ProjectsDropdown";
import { PlatformSelector } from "@/components/PlatformSelector";
import { IntegrationsPanel } from "@/components/IntegrationsPanel";
const personas = [
  {
    id: "solo",
    label: "Solo developer",
    headline: "Ship full-stack apps without boilerplate.",
    bullets: [
      "One editor for web and mobile screens.",
      "Autogenerated Supabase schema and queries.",
      "Inline AI help for layout, copy, and code.",
    ],
  },
  {
    id: "team",
    label: "Product team",
    headline: "Design, build, and ship from one workspace.",
    bullets: [
      "Live collaboration with change history.",
      "GitHub integration for reviews and PRs.",
      "AI agents to generate flows and tests.",
    ],
  },
  {
    id: "agency",
    label: "Agency / Studio",
    headline: "Manage dozens of client apps from one cloud.",
    bullets: [
      "Dedicated workspaces per client.",
      "Token and cost controls per project.",
      "Template libraries you can reuse and resell.",
    ],
  },
];

const ideaCategories = [
  {
    id: "saas",
    label: "SaaS apps",
    ideas: [
      "Subscription dashboard for creators",
      "Analytics panel for small businesses",
      "Multi-tenant CRM for agencies",
    ],
  },
  {
    id: "social",
    label: "Communities",
    ideas: ["Learning community for developers", "Niche social network for artists", "Private members club platform"],
  },
  {
    id: "marketplace",
    label: "Marketplaces",
    ideas: ["Service marketplace for local jobs", "Digital asset marketplace", "Peer-to-peer rentals app"],
  },
];

const featureCards = [
  {
    title: "Smart UI Builder",
    description: "Generate beautiful layouts instantly with clean, production-ready code.",
  },
  {
    title: "Error-Aware Code Assist",
    description: "UR-DEV analyzes and fixes your code while keeping everything aligned.",
  },
  {
    title: "Scalable Projects",
    description: "Handle complex files and long projects without slowing down.",
  },
  {
    title: "Theme & Style Engine",
    description: "Create consistent themes, palettes, and animations for your projects.",
  },
];

const agentCards = [
  {
    title: "UI Agent",
    subtitle: "Layout and styling",
    description: "Takes your prompt and reshapes the page without breaking code.",
  },
  {
    title: "Schema Agent",
    subtitle: "Database design",
    description: "Designs tables, relationships, and migrations for Supabase.",
  },
  {
    title: "Deploy Agent",
    subtitle: "Shipping & checks",
    description: "Previews diffs, runs checks, and ships safely to production.",
  },
];

const galleryFilters = [
  { id: "featured", label: "Highlights" },
  { id: "discover", label: "Discover" },
  { id: "web", label: "Web apps" },
  { id: "mobile", label: "Mobile" },
  { id: "internal", label: "Internal tools" },
  { id: "prototype", label: "Prototypes" },
];

const galleryProjects = [
  {
    id: 1,
    title: "Studio launch workspace",
    category: "web",
    badge: "Website",
    authorInitial: "S",
    authorHandle: "studio-launch",
    remixCount: 123,
  },
  {
    id: 2,
    title: "Learning hub dashboard",
    category: "internal",
    badge: "Internal tool",
    authorInitial: "L",
    authorHandle: "learning-hub",
    remixCount: 88,
  },
  {
    id: 3,
    title: "Creator subscription page",
    category: "web",
    badge: "Website",
    authorInitial: "C",
    authorHandle: "creator-subscribe",
    remixCount: 204,
  },
  {
    id: 4,
    title: "City guide mobile app",
    category: "mobile",
    badge: "Mobile",
    authorInitial: "G",
    authorHandle: "guide-city",
    remixCount: 47,
  },
  {
    id: 5,
    title: "Task board for teams",
    category: "internal",
    badge: "Internal tool",
    authorInitial: "T",
    authorHandle: "team-board",
    remixCount: 156,
  },
  {
    id: 6,
    title: "Freelancer portfolio layout",
    category: "web",
    badge: "Website",
    authorInitial: "F",
    authorHandle: "freelance-portfolio",
    remixCount: 61,
  },
  {
    id: 7,
    title: "Bookings mobile flow",
    category: "mobile",
    badge: "Mobile",
    authorInitial: "B",
    authorHandle: "booking-flow",
    remixCount: 39,
  },
  {
    id: 8,
    title: "Finance overview prototype",
    category: "prototype",
    badge: "Prototype",
    authorInitial: "P",
    authorHandle: "proto-finance",
    remixCount: 12,
  },
];

const UrDevLandingPage: React.FC = () => {
  const [hasScrolled, setHasScrolled] = useState(false);
  const [promptMode, setPromptMode] = useState<"website" | "mobile" | "dashboard">("website");
  const [prompt, setPrompt] = useState("");
  const [promptStatus, setPromptStatus] = useState("Draft");
  const [activePersonaId, setActivePersonaId] = useState("solo");
  const [selectedIdeaCategoryId, setSelectedIdeaCategoryId] = useState("saas");
  const [activeGalleryFilter, setActiveGalleryFilter] = useState("featured");
  const promptTextareaRef = useRef<HTMLTextAreaElement | null>(null);
  const navigate = useNavigate();
  const { toast } = useToast();
  const [user, setUser] = useState<SupabaseUser | null>(null);
  const [authReady, setAuthReady] = useState(false);
  const [isAdmin, setIsAdmin] = useState(false);
  const [showPlanWizard, setShowPlanWizard] = useState(false);
  const [showPlatformSelector, setShowPlatformSelector] = useState(false);
  const [selectedPlatform, setSelectedPlatform] = useState<"website" | "mobile" | "both" | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [showIntegrationsPanel, setShowIntegrationsPanel] = useState(false);

  const handlePlatformSelect = (platform: "website" | "mobile" | "both") => {
    setSelectedPlatform(platform);
    setShowPlatformSelector(false);
    setShowPlanWizard(true);
    
    // Update prompt mode based on selection
    if (platform === "website") {
      setPromptMode("website");
    } else if (platform === "mobile") {
      setPromptMode("mobile");
    }
  };

  const handleCreateProject = (planData: PlanData) => {
    const newProject: Project = {
      id: crypto.randomUUID(),
      name: planData.projectName || `New ${planData.projectType}`,
      type: planData.projectType === "mobile-app" ? "mobile" : 
            planData.projectType === "dashboard" ? "dashboard" : "website",
      description: planData.projectName?.slice(0, 100),
      createdAt: new Date(),
    };
    setProjects((prev) => [newProject, ...prev]);
    setShowPlanWizard(false);
    toast({
      title: "Project Created",
      description: `${newProject.name} has been added to your projects.`,
    });
  };

  const handleSelectProject = (project: Project) => {
    toast({
      title: "Opening Project",
      description: `Opening ${project.name}...`,
    });
    navigate("/");
  };
  useEffect(() => {
    const fetchUserRole = async (userId: string) => {
      try {
        const { data: roleData } = await supabase
          .from("user_roles")
          .select("role")
          .eq("user_id", userId)
          .in("role", ["owner", "admin"])
          .maybeSingle();

        setIsAdmin(!!roleData);
      } catch (error) {
        console.error("Error fetching user role", error);
        setIsAdmin(false);
      }
    };

    const checkUser = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      setUser(session?.user ?? null);

      if (session?.user) {
        await fetchUserRole(session.user.id);
      } else {
        setIsAdmin(false);
      }

      setAuthReady(true);
    };

    checkUser();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);

      if (session?.user) {
        setIsAdmin(false);
        setTimeout(() => {
          fetchUserRole(session.user!.id);
        }, 0);
      } else {
        setIsAdmin(false);
      }

      setAuthReady(true);
    });

    return () => subscription.unsubscribe();
  }, []);

  const handleOAuthLogin = async (provider: "google" | "github") => {
    try {
      const { error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: `${window.location.origin}/`,
        },
      });

      if (error) throw error;
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || `Failed to login with ${provider}`,
        variant: "destructive",
      });
    }
  };

  const handleLogout = async () => {
    console.log("Sign Out button clicked");
    try {
      const { error } = await supabase.auth.signOut();
      if (error) throw error;
      
      console.log("Supabase signOut successful");
      
      // Clear admin session
      sessionStorage.removeItem("admin_authenticated");
      setIsAdmin(false);
      setUser(null);

      toast({
        title: "Success",
        description: "Logged out successfully",
      });

      navigate("/");
    } catch (error: any) {
      console.error("Error during logout", error);
      toast({
        title: "Error",
        description: error.message || "Failed to logout",
        variant: "destructive",
      });
    }
  };

  const getUserInitial = () => {
    if (!user?.email) return "U";
    return user.email.charAt(0).toUpperCase();
  };

  const activePersona = personas.find((p) => p.id === activePersonaId)!;
  const selectedCategory = ideaCategories.find((c) => c.id === selectedIdeaCategoryId)!;

  const visibleProjects = galleryProjects.filter((project) => {
    if (activeGalleryFilter === "featured") return true;
    if (activeGalleryFilter === "discover") return true;
    return project.category === activeGalleryFilter;
  });

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 8) {
        setHasScrolled(true);
      } else {
        setHasScrolled(false);
      }
    };

    handleScroll();
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    const el = promptTextareaRef.current;
    if (!el) return;

    const computed = window.getComputedStyle(el);
    const lineHeight = parseFloat(computed.lineHeight || "20");
    const minRows = 4;
    const maxRows = 8;
    const minHeight = lineHeight * minRows;
    const maxHeight = lineHeight * maxRows;

    el.style.height = "auto";
    const nextHeight = Math.min(Math.max(el.scrollHeight, minHeight), maxHeight);
    el.style.height = `${nextHeight}px`;
    el.style.overflowY = el.scrollHeight > maxHeight ? "auto" : "hidden";
  }, [prompt]);

  const handleUseSamplePrompt = () => {
    if (promptMode === "website") {
      setPrompt("Create a landing page for a SaaS that helps teams design, build, and ship apps with AI.");
    } else if (promptMode === "mobile") {
      setPrompt("Design a mobile app with onboarding, home feed, and profile for a learning community.");
    } else {
      setPrompt("Generate an analytics dashboard with charts for active users, revenue, and errors.");
    }
    setPromptStatus("Ready to build");
  };

  const handleBuildClick = () => {
    if (!prompt.trim()) {
      handleUseSamplePrompt();
      return;
    }
    setPromptStatus("Analyzing prompt with AI agents");
    setTimeout(() => {
      setPromptStatus("Draft layout generated – open the IDE to refine.");
    }, 800);
  };

  const promptPlaceholder =
    promptMode === "website"
      ? "Describe the website you want to build with UR-DEV…"
      : promptMode === "mobile"
        ? "Describe the mobile app you want to build with UR-DEV…"
        : "Describe the dashboard or internal tool you want UR-DEV to assemble…";

  return (
    <div className="min-h-screen bg-[#020617] text-gray-100 flex flex-col">
      <header
        className={`sticky top-0 z-20 transition-colors ${
          hasScrolled
            ? "border-b border-white/10 bg-black/80 backdrop-blur"
            : "border-b border-transparent bg-transparent"
        }`}
      >
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-500/20 border border-cyan-400/60 text-xs font-semibold text-cyan-200">
              UR
            </div>
            <div>
              <div className="text-sm font-semibold tracking-tight">UR-DEV</div>
              <div className="text-[10px] uppercase tracking-[0.18em] text-gray-500">YOU ARE THE DEVELOPER</div>
            </div>
          </div>
          <nav className="hidden gap-6 text-xs text-gray-300 sm:flex items-center">
            {projects.length > 0 && (
              <ProjectsDropdown
                projects={projects}
                onNewProject={() => setShowPlatformSelector(true)}
                onSelectProject={handleSelectProject}
              />
            )}
            <a href="#frames" className="hover:text-white">
              Builder
            </a>
            <a href="#ideas" className="hover:text-white">
              Ideas
            </a>
            <a href="#agents" className="hover:text-white">
              AI Agents
            </a>
            <a href="#features" className="hover:text-white">
              Features
            </a>
          </nav>
          <div className="flex items-center gap-2 text-xs">
            {!authReady ? (
              <div className="h-9 w-9" />
            ) : user ? (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <button className="h-9 w-9 rounded-xl bg-neutral-700 flex items-center justify-center text-sm font-semibold hover:bg-neutral-600 transition focus:outline-none focus:ring-0">
                    {getUserInitial()}
                  </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent 
                  align="end"
                  className="w-72 bg-neutral-900 text-neutral-100 rounded-2xl shadow-2xl p-4 border border-neutral-800 z-[9999]"
                  style={{ backgroundColor: 'rgb(23, 23, 23)' }}
                >
                  {/* User Info */}
                  <div className="flex items-center gap-4 pb-4 border-b border-neutral-800">
                    <div className="h-12 w-12 rounded-xl bg-neutral-700 flex items-center justify-center text-lg font-semibold">
                      {getUserInitial()}
                    </div>
                    <div>
                      <p className="font-semibold text-sm">UR-DEV Workspace</p>
                      <p className="text-neutral-400 text-xs">{user.email}</p>
                    </div>
                  </div>

                  {/* Credits */}
                  <div className="mt-4 p-3 rounded-xl bg-neutral-800 border border-neutral-700">
                    <div className="flex justify-between text-sm mb-2">
                      <span>Credits</span>
                      <span className="text-neutral-300">2,450 left</span>
                    </div>
                    <div className="w-full h-2 bg-neutral-700 rounded-full overflow-hidden">
                      <div className="h-full w-1/3 bg-neutral-300 rounded-full"></div>
                    </div>
                  </div>

                  {/* Buttons */}
                  <div className="mt-4 space-y-2">
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm focus:outline-none focus:ring-0">
                      <Users className="h-4 w-4" /> Team & Members
                      <span className="ml-auto bg-neutral-700 text-neutral-300 text-xs px-2 py-0.5 rounded-md">0</span>
                      <span className="ml-2 bg-neutral-600 text-neutral-200 text-[10px] px-2 py-0.5 rounded-md">Add</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm focus:outline-none focus:ring-0">
                      <CreditCard className="h-4 w-4" /> Billing & Credits
                      <span className="ml-auto bg-neutral-700 text-neutral-300 text-xs px-2 py-0.5 rounded-md">3</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm focus:outline-none focus:ring-0">
                      <Briefcase className="h-4 w-4" /> Workspace Manager
                      <span className="ml-auto bg-neutral-700 text-neutral-300 text-xs px-2 py-0.5 rounded-md">Create</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm focus:outline-none focus:ring-0 mt-1">
                      <span className="h-1.5 w-1.5 bg-neutral-400 rounded-full"></span>
                      <span className="text-neutral-300">New Workspace</span>
                      <span className="ml-auto bg-neutral-700 text-neutral-300 text-xs px-2 py-0.5 rounded-md">+ Create new</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm focus:outline-none focus:ring-0">
                      <Bell className="h-4 w-4" /> Notifications
                      <span className="ml-auto bg-red-600 text-white text-xs px-2 py-0.5 rounded-md">5</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm">
                      <HelpCircle className="h-4 w-4" /> Help Center
                      <span className="ml-auto text-neutral-500">➜</span>
                    </button>
                    <button className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm">
                      <Sun className="h-4 w-4" /> Appearance
                    </button>
                    {user && (
                      <button 
                        onClick={() => navigate("/admin/login")}
                        className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-neutral-800 transition text-sm text-blue-400 focus:outline-none focus:ring-0"
                      >
                        <Settings className="h-4 w-4" /> Admin Panel
                        <span className="ml-auto text-[10px] bg-blue-500/20 text-blue-300 px-2 py-0.5 rounded-md">Admin</span>
                      </button>
                    )}

                  </div>

                  {/* Sign Out - Separated and clearly marked */}
                  <div className="mt-4 pt-4 border-t border-neutral-700">
                    <button 
                      onClick={handleLogout}
                      className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-red-900/20 transition text-sm text-red-400 font-semibold border border-red-900/30 hover:border-red-800/50"
                    >
                      <LogOut className="h-4 w-4" /> Sign Out (Logout)
                    </button>
                  </div>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <button className="rounded-full border border-white/20 bg-transparent px-3 py-1.5 text-gray-200 hover:border-cyan-400/80 hover:text-cyan-100 transition focus:outline-none focus:ring-0 focus:border-white/20">
                      Sign In
                    </button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="w-96 bg-neutral-900 border-neutral-700 z-50 p-6">
                    <div className="flex flex-col items-center">
                      {/* Title */}
                      <h2 className="text-2xl font-bold mb-6 text-white">UR-DEV</h2>
                      
                      {/* Buttons */}
                      <div className="space-y-3 w-full">
                        <DropdownMenuItem 
                          className="flex items-center justify-center gap-3 w-full py-3 rounded-full bg-neutral-800 hover:bg-neutral-700 text-neutral-100 text-sm border border-neutral-700 transition shadow-lg cursor-pointer focus:bg-neutral-700"
                          onSelect={() => handleOAuthLogin("google")}
                        >
                          <svg className="h-5 w-5" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                            <path d="M263.821537,7247.00386 L254.211298,7247.00386 C254.211298,7248.0033 254.211298,7250.00218 254.205172,7251.00161 L259.774046,7251.00161 C259.560644,7252.00105 258.804036,7253.40026 257.734984,7254.10487 C257.733963,7254.10387 257.732942,7254.11086 257.7309,7254.10986 C256.309581,7255.04834 254.43389,7255.26122 253.041161,7254.98137 C250.85813,7254.54762 249.130492,7252.96451 248.429023,7250.95364 C248.433107,7250.95064 248.43617,7250.92266 248.439233,7250.92066 C248.000176,7249.67336 248.000176,7248.0033 248.439233,7247.00386 L248.438212,7247.00386 C249.003881,7245.1669 250.783592,7243.49084 252.969687,7243.0321 C254.727956,7242.65931 256.71188,7243.06308 258.170978,7244.42831 C258.36498,7244.23842 260.856372,7241.80579 261.043226,7241.6079 C256.0584,7237.09344 248.076756,7238.68155 245.090149,7244.51127 L245.089128,7244.51127 C245.089128,7244.51127 245.090149,7244.51127 245.084023,7244.52226 L245.084023,7244.52226 C243.606545,7247.38565 243.667809,7250.75975 245.094233,7253.48622 C245.090149,7253.48921 245.087086,7253.49121 245.084023,7253.49421 C246.376687,7256.0028 248.729215,7257.92672 251.563684,7258.6593 C254.574796,7259.44886 258.406843,7258.90916 260.973794,7256.58747 C260.974815,7256.58847 260.975836,7256.58947 260.976857,7256.59047 C263.15172,7254.63157 264.505648,7251.29445 263.821537,7247.00386" transform="translate(-244.000000, -7239.000000)"/>
                          </svg>
                          Continue with Google
                        </DropdownMenuItem>

                        <DropdownMenuItem 
                          className="flex items-center justify-center gap-3 w-full py-3 rounded-full bg-neutral-800 hover:bg-neutral-700 text-neutral-100 text-sm border border-neutral-700 transition shadow-lg cursor-pointer focus:bg-neutral-700"
                          onSelect={() => handleOAuthLogin("github")}
                        >
                          <Github className="h-5 w-5" />
                          Continue with GitHub
                        </DropdownMenuItem>

                        <Link to="/login" className="block">
                          <DropdownMenuItem className="flex items-center justify-center gap-3 w-full py-3 rounded-full bg-neutral-800 hover:bg-neutral-700 text-neutral-100 text-sm border border-neutral-700 transition shadow-lg cursor-pointer focus:bg-neutral-700">
                            <Mail className="h-5 w-5" />
                            Sign in with Email
                          </DropdownMenuItem>
                        </Link>
                      </div>

                      {/* Terms */}
                      <p className="text-neutral-500 text-xs mt-6 text-center">
                        By signing in, you agree to the{" "}
                        <a href="#" className="text-neutral-300 hover:text-white hover:underline">
                          UR-DEV Terms
                        </a>{" "}
                        and{" "}
                        <a href="#" className="text-neutral-300 hover:text-white hover:underline">
                          Privacy Policy
                        </a>
                        .
                      </p>
                    </div>
                  </DropdownMenuContent>
                </DropdownMenu>
                <Link
                  to="/register"
                  className="rounded-full bg-cyan-500 px-4 py-1.5 text-[11px] font-semibold text-black shadow-[0_0_20px_rgba(34,211,238,0.6)] hover:bg-cyan-400"
                >
                  Launch IDE
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      <main className="flex-1">
        <section className="px-4 pt-10 pb-16 sm:px-6 lg:px-8">
          <div className="mx-auto flex max-w-5xl flex-col items-center text-center gap-6">

            <div className="space-y-3">
              <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl lg:text-5xl">
                UR-DEV – Build web & mobile apps with
                <span className="bg-gradient-to-r from-cyan-300 via-sky-400 to-indigo-300 bg-clip-text text-transparent">
                  {" "}
                  real databases
                </span>{" "}
                and
                <span className="bg-gradient-to-r from-emerald-300 to-teal-400 bg-clip-text text-transparent">
                  {" "}
                  AI agents
                </span>
                .
              </h1>
              <p className="max-w-2xl text-sm text-gray-400 mx-auto leading-relaxed">
                Build production-ready apps in minutes. From pixel-perfect UI design to seamless database integration, 
                our AI-powered platform handles the complexity while you focus on what matters most.
              </p>
            </div>

            <section className="w-full max-w-3xl">
              <div className="flex flex-wrap items-center justify-between gap-3 text-xs">
                <div className="inline-flex flex-wrap gap-2">
                  <button
                    type="button"
                    onClick={() => setPromptMode("website")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "website"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Create a website
                  </button>
                  <button
                    type="button"
                    onClick={() => setPromptMode("mobile")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "mobile"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Build a mobile app
                  </button>
                  <button
                    type="button"
                    onClick={() => setPromptMode("dashboard")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "dashboard"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Design a dashboard
                  </button>
                </div>
              </div>
              <div className="mt-4 text-left w-full">
                <div className="relative rounded-3xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.35),_transparent_65%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.4),_transparent_70%)] p-[1px] shadow-[0_0_45px_rgba(15,23,42,0.9)]">
                  <div className="relative rounded-[22px] border-[0.5px] border-gray-700 bg-neutral-800 px-4 pt-6 pb-16 sm:px-5 sm:pt-8 sm:pb-20">
                    <textarea
                      ref={promptTextareaRef}
                      rows={4}
                      value={prompt}
                      onChange={(e) => {
                        setPrompt(e.target.value);
                        setPromptStatus("Draft");
                      }}
                      placeholder="Hey UR-Dev, let's go!"
                      spellCheck={true}
                      className="w-full bg-transparent border-none outline-none text-base text-white/80 placeholder:text-white/50 resize-none px-0 py-1 selection:bg-sky-500/40 selection:text-white overflow-y-auto scrollbar-white"
                    />
                  <button
                    type="button"
                    onClick={handleBuildClick}
                    className="absolute bottom-4 right-4 sm:bottom-5 sm:right-5 inline-flex items-center gap-2 rounded-full bg-sky-500 px-4 py-1.5 text-[11px] font-semibold text-black shadow-[0_0_26px_rgba(59,130,246,0.9)] hover:bg-sky-400"
                  >
                    <span>Build with UR-DEV</span>
                    <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-black/20 text-[10px]">
                      →
                    </span>
                  </button>
                  <div className="absolute bottom-4 left-4 right-20 sm:right-24 sm:bottom-5 sm:left-5 flex flex-wrap items-center gap-1.5 sm:gap-2 text-[11px] text-gray-300">
                      <button className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-2.5 sm:px-3 py-1 hover:border-cyan-400/80 hover:text-cyan-100 text-[10px] sm:text-[11px]">
                        <span className="text-xs">＋</span>
                        <span>Attach</span>
                      </button>
                      <button 
                        onClick={() => setShowIntegrationsPanel(true)}
                        className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-2.5 sm:px-3 py-1 hover:border-purple-400/80 hover:text-purple-100 text-[10px] sm:text-[11px]"
                      >
                        <Plug className="h-3 w-3" />
                        <span>Integration</span>
                      </button>
                      <button 
                        onClick={() => setShowPlatformSelector(true)}
                        className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-2.5 sm:px-3 py-1 hover:border-sky-400/80 hover:text-sky-100 text-[10px] sm:text-[11px]"
                      >
                        <ListTodo className="h-3 w-3" />
                        <span>Make the Plan</span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Visual Showcase: Website + Mobile Frame */}
              <div className="mt-8 relative pb-24 sm:pb-16">
                {/* Desktop/Website Frame */}
                <div className="relative rounded-2xl border border-gray-700 bg-neutral-800 p-3 sm:p-4 shadow-[0_0_80px_rgba(15,23,42,0.85)]">
                  <div className="flex items-center gap-2 mb-2 sm:mb-3 pb-2 border-b border-gray-700">
                    <div className="flex gap-1.5">
                      <div className="h-2 w-2 sm:h-2.5 sm:w-2.5 rounded-full bg-destructive/80"></div>
                      <div className="h-2 w-2 sm:h-2.5 sm:w-2.5 rounded-full bg-warning/80"></div>
                      <div className="h-2 w-2 sm:h-2.5 sm:w-2.5 rounded-full bg-success/80"></div>
                    </div>
                    <div className="flex-1 flex justify-center">
                      <div className="rounded-full bg-muted px-3 sm:px-4 py-1 text-[9px] sm:text-[10px] text-muted-foreground">
                        your-app.urdev.app
                      </div>
                    </div>
                  </div>
                  <div className="aspect-video rounded-lg bg-background border border-ide-border overflow-hidden">
                    <div className="p-3 sm:p-4 space-y-3 sm:space-y-4 flex flex-col md:flex-row gap-3 md:gap-4">
                      {/* Left: Hero text */}
                      <div className="flex-1 space-y-2 sm:space-y-3">
                        <div className="inline-flex items-center gap-1.5 rounded-full border border-primary/40 bg-primary/10 px-2.5 py-0.5 text-[8px] sm:text-[9px] text-primary-foreground/80">
                          <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse" />
                          <span>UR-DEV – Build web &amp; mobile apps with real databases and AI agents</span>
                        </div>
                        <h2 className="text-xs sm:text-sm font-semibold text-foreground leading-snug">
                          UR-DEV – Build web &amp; mobile apps with <span className="text-primary">real databases</span> and <span className="text-primary">AI agents</span>.
                        </h2>
                        <p className="text-[8px] sm:text-[9px] text-muted-foreground max-w-xs">
                          Visual editor for web and mobile screens, native Supabase &amp; GitHub integration, plus AI agents that understand your schema, your files, and your deployments.
                        </p>
                        <div className="flex flex-wrap items-center gap-1.5 sm:gap-2">
                          <div className="h-5 sm:h-6 flex-1 rounded-md border border-border bg-background/60 text-[8px] sm:text-[9px] text-muted-foreground flex items-center px-2">
                            Describe the website you want to build with UR-DEV…
                          </div>
                          <button className="rounded-full bg-primary px-2.5 py-1 text-[8px] sm:text-[9px] font-semibold text-primary-foreground shadow-sm">
                            Build with UR-DEV
                          </button>
                        </div>
                      </div>

                      {/* Right: Mini cards */}
                      <div className="flex-1 grid grid-cols-2 gap-2 sm:gap-3 self-stretch">
                        <div className="col-span-2 h-10 sm:h-12 rounded-lg border border-border bg-card" />
                        <div className="h-10 sm:h-12 rounded-lg border border-border bg-card" />
                        <div className="h-10 sm:h-12 rounded-lg border border-border bg-card" />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Mobile Frame - Overlaying on the right side */}
                <div className="absolute -bottom-12 right-4 w-32 sm:-bottom-16 sm:right-6 sm:w-48 md:bottom-16 md:right-8 md:w-56 z-10">
                  <div className="relative rounded-[1.5rem] sm:rounded-[2rem] border-[3px] sm:border-4 border-foreground/10 bg-background shadow-[0_15px_40px_rgba(0,0,0,0.8)] sm:shadow-[0_20px_60px_rgba(0,0,0,0.8)]">
                    {/* Phone notch */}
                    <div className="absolute top-0 left-1/2 -translate-x-1/2 w-16 sm:w-24 h-4 sm:h-5 bg-background rounded-b-xl sm:rounded-b-2xl z-20"></div>
                    
                    {/* Screen */}
                    <div className="aspect-[9/19.5] rounded-[1.2rem] sm:rounded-[1.7rem] bg-background border border-ide-border overflow-hidden">
                      <div className="p-2 sm:p-3 pt-8 sm:pt-12 space-y-2 sm:space-y-2.5 flex flex-col">
                        {/* Mobile Header */}
                        <div className="flex items-center justify-center gap-1">
                          <div className="flex h-3 w-3 sm:h-4 sm:w-4 items-center justify-center rounded bg-primary/15 border border-primary/50 text-[6px] sm:text-[7px] font-semibold text-primary-foreground">
                            UR
                          </div>
                          <span className="text-[7px] sm:text-[8px] font-semibold text-foreground">UR-DEV</span>
                        </div>
                        
                        {/* Mobile Content */}
                        <div className="space-y-0.5 text-center">
                          <h3 className="text-[8px] sm:text-[9px] font-semibold text-foreground leading-tight">
                            Build app with <span className="text-primary">AI agents</span>
                          </h3>
                          <p className="text-[6px] sm:text-[7px] text-muted-foreground">
                            UR-DEV – Web &amp; mobile editor
                          </p>
                        </div>
                        
                        {/* Mobile Input */}
                        <div className="rounded bg-background/60 border border-border p-1.5 sm:p-2">
                          <div className="h-6 sm:h-8 bg-transparent border border-border rounded text-[6px] sm:text-[7px] text-muted-foreground flex items-center px-1.5">
                            Describe the app you want to build…
                          </div>
                        </div>
                        
                        {/* Mobile List */}
                        <div className="space-y-1 sm:space-y-1.5 flex-1">
                          <div className="h-7 sm:h-8 bg-card rounded border border-border" />
                          <div className="h-7 sm:h-8 bg-card rounded border border-border" />
                          <div className="h-7 sm:h-8 bg-card rounded border border-border" />
                        </div>
                      </div>
                    </div>
                    
                    {/* Home indicator */}
                    <div className="absolute bottom-0.5 sm:bottom-1 left-1/2 -translate-x-1/2 w-14 sm:w-20 h-0.5 sm:h-1 bg-foreground/20 rounded-full"></div>
                  </div>
                </div>
              </div>

            </section>
          </div>
        </section>

        <section id="frames" className="border-t border-white/5 px-4 py-12 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-6xl">
            <div className="rounded-[32px] border border-white/10 bg-gradient-to-b from-slate-900/80 to-black/95 p-5 sm:p-6 shadow-[0_0_60px_rgba(15,23,42,0.9)] space-y-6">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                <div>
                  <div className="text-[11px] uppercase tracking-[0.18em] text-gray-500">UR-DEV workspace</div>
                  <h2 className="mt-1 text-xl font-semibold text-white">Explore what the community is building</h2>
                  <p className="text-sm text-gray-400 max-w-xl">
                    Browse example workspaces across different types of projects. Each card represents something you
                    could assemble in your own editor.
                  </p>
                </div>
                <button className="self-start rounded-full border border-white/20 bg-white/5 px-4 py-1.5 text-[11px] text-gray-200 hover:border-cyan-400/80 hover:text-cyan-100">
                  View all workspaces
                </button>
              </div>

              <div className="flex flex-wrap items-center gap-2 text-xs">
                {galleryFilters.map((filter) => (
                  <button
                    key={filter.id}
                    type="button"
                    onClick={() => setActiveGalleryFilter(filter.id)}
                    className={`rounded-full border px-3 py-1 ${
                      activeGalleryFilter === filter.id
                        ? "border-cyan-400/80 bg-cyan-500/20 text-cyan-100"
                        : "border-white/20 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    {filter.label}
                  </button>
                ))}
              </div>

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {visibleProjects.map((project) => (
                  <div
                    key={project.id}
                    className="group relative flex flex-col overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-slate-900 to-black p-3 text-[11px] text-gray-300 hover:border-cyan-400/70 hover:bg-slate-900/90 transition"
                  >
                    <div className="mb-2 aspect-[4/3] w-full overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.25),_transparent_55%),_radial-gradient(circle_at_bottom,_rgba(167,139,250,0.22),_transparent_55%)]" />
                    <div className="mt-2 flex-1">
                      <div className="flex items-center justify-between gap-2">
                        <h3 className="truncate text-[12px] font-semibold text-white">{project.title}</h3>
                        <span className="whitespace-nowrap rounded-full border border-white/15 bg-white/5 px-2 py-0.5 text-[10px] text-gray-300">
                          {project.badge}
                        </span>
                      </div>
                      <div className="mt-2 flex items-center justify-between text-[10px] text-gray-400">
                        <div className="flex items-center gap-2">
                          <div className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-semibold text-gray-100">
                            {project.authorInitial}
                          </div>
                          <span className="truncate max-w-[90px]">{project.authorHandle}</span>
                        </div>
                        <span>{project.remixCount} copies</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="ideas" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-6xl space-y-14">
            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-white sm:text-3xl">Build smarter, not harder</h2>
                <p className="text-sm text-gray-400 max-w-xl">
                  UR-DEV understands what you are trying to build and generates clean, stable code that fits your stack.
                  Spend your time on ideas instead of boilerplate.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Instant component layouts with sensible defaults and full styling.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Automatic checks that flag broken props, missing imports, and typos.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Refactor suggestions that keep your UI and codebase easy to grow.</span>
                  </li>
                </ul>
              </div>

              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(59,130,246,0.35),_transparent_60%)]">
                  <span className="text-3xl text-sky-200">{"<>"}</span>
                </div>
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center order-last lg:order-first">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(45,212,191,0.28),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.32),_transparent_60%)]">
                  <span className="text-3xl text-emerald-200">↗</span>
                </div>
              </div>

              <div className="space-y-4 order-first lg:order-last">
                <h3 className="text-2xl font-semibold text-white sm:text-3xl">Your workflow—accelerated</h3>
                <p className="text-sm text-gray-400 max-w-xl">
                  From first idea to production, UR-DEV keeps the same project connected: prompts, editor, database, and
                  deployments all stay in sync.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Real-time preview that mirrors what your users will see on web and mobile.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Git-backed history so every change can be reviewed, reverted, or replayed.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>One-click deploys that ship the exact build you tested in the editor.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section id="agents" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-6xl space-y-14">
            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-white sm:text-3xl">Stay in control</h2>
                <p className="text-sm text-gray-400 max-w-xl">
                  Every suggestion stays visible and reversible. UR-DEV highlights what is changing so you can approve,
                  tweak, or roll back with confidence.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Clear diff views for layout, code, and schema edits.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Undo and redo with full history across prompts and manual edits.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Safe mode that prevents destructive changes to production data.</span>
                  </li>
                </ul>
              </div>

              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(94,234,212,0.32),_transparent_60%)]">
                  <span className="text-3xl text-sky-200">🎛️</span>
                </div>
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center order-last lg:order-first">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(244,114,182,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.32),_transparent_60%)]">
                  <span className="text-3xl text-pink-200">🎨</span>
                </div>
              </div>

              <div className="space-y-4 order-first lg:order-last">
                <h3 className="text-2xl font-semibold text-white sm:text-3xl">Create your own design language</h3>
                <p className="text-sm text-gray-400 max-w-xl">
                  Define tokens once and reuse them everywhere. UR-DEV keeps your color, spacing, and component
                  decisions consistent across pages and platforms.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Custom palettes for brand colors, typography, and elevation.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Reusable components for headers, forms, and interactive blocks.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Responsive rules that keep layouts balanced on desktop and mobile.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section id="features" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-4xl text-center space-y-4">
            <h2 className="text-2xl font-semibold text-white sm:text-3xl">Ready to start your next project?</h2>
            <p className="text-sm text-gray-400 max-w-xl mx-auto">
              Move from idea to running app in a single workspace. UR-DEV connects prompts, editor, database, and
              deployments so you can focus on shipping.
            </p>
            <div className="pt-2 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
              <a
                href="/register"
                className="rounded-full bg-sky-500 px-6 py-2 text-sm font-semibold text-black shadow-[0_0_26px_rgba(59,130,246,0.7)] hover:bg-sky-400"
              >
                Start Building Now
              </a>
              <span className="text-[11px] text-gray-500">
                Join early teams using UR-DEV for web and mobile workspaces.
              </span>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-white/10 bg-black/95 text-[11px] text-gray-500">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
          <div className="flex flex-col gap-8 md:flex-row md:justify-between">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-500/20 border border-cyan-400/60 text-xs font-semibold text-cyan-200">
                  UR
                </div>
                <span className="text-sm font-semibold text-gray-100">UR-DEV</span>
              </div>
              <p className="max-w-xs text-[11px] text-gray-500">
                A focused workspace for building web and mobile apps with real databases, GitHub, and AI agents.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-6 sm:grid-cols-4 text-[11px]">
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Product</div>
                <a href="#frames" className="block hover:text-cyan-200">
                  Builder
                </a>
                <a href="#agents" className="block hover:text-cyan-200">
                  AI agents
                </a>
                <a href="#ideas" className="block hover:text-cyan-200">
                  Workflows
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Resources</div>
                <a href="/docs" className="block hover:text-cyan-200">
                  Documentation
                </a>
                <a href="/templates" className="block hover:text-cyan-200">
                  Templates
                </a>
                <a href="/changelog" className="block hover:text-cyan-200">
                  Changelog
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Company</div>
                <a href="/about" className="block hover:text-cyan-200">
                  About
                </a>
                <a href="/blog" className="block hover:text-cyan-200">
                  Blog
                </a>
                <a href="/careers" className="block hover:text-cyan-200">
                  Careers
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Legal</div>
                <a href="/terms" className="block hover:text-cyan-200">
                  Terms
                </a>
                <a href="/privacy" className="block hover:text-cyan-200">
                  Privacy
                </a>
                <a href="/security" className="block hover:text-cyan-200">
                  Security
                </a>
              </div>
            </div>
          </div>

          <div className="mt-6 flex flex-col items-start justify-between gap-3 border-t border-white/10 pt-4 sm:flex-row sm:items-center">
            <span>© {new Date().getFullYear()} UR-DEV. All rights reserved.</span>
            <div className="flex gap-4 text-[11px]">
              <a href="https://twitter.com" className="hover:text-cyan-200">
                Twitter
              </a>
              <a href="https://discord.com" className="hover:text-cyan-200">
                Discord
              </a>
            </div>
          </div>
        </div>
      </footer>

      {/* Plan Wizard */}
      <PlanWizard
        open={showPlanWizard}
        onClose={() => setShowPlanWizard(false)}
        onGeneratePlan={(planData: PlanData) => {
          // Add to projects list
          handleCreateProject(planData);
          
          const featuresList = planData.features.length > 0 
            ? `Key features: ${planData.features.join(", ")}. ` 
            : "";
          
          const additionalInfo = planData.additionalDetails.trim() 
            ? `Requirements: ${planData.additionalDetails}` 
            : "";

          const generatedPrompt = `Build a ${planData.projectType} project called "${planData.projectName}". ${featuresList}${additionalInfo}`;
          
          setPrompt(generatedPrompt);
          setPromptStatus("Plan ready");
          
          // Navigate to editor with the plan
          navigate('/editor');
        }}
      />

      {/* Platform Selector */}
      <PlatformSelector
        open={showPlatformSelector}
        onClose={() => setShowPlatformSelector(false)}
        onSelect={handlePlatformSelect}
      />

      {/* Integrations Panel */}
      <IntegrationsPanel
        open={showIntegrationsPanel}
        onClose={() => setShowIntegrationsPanel(false)}
      />
    </div>
  );
};

export default UrDevLandingPage;
