import React, { useEffect, useState } from "react";

const personas = [
  {
    id: "solo",
    label: "Solo developer",
    headline: "Ship full-stack apps without boilerplate.",
    bullets: [
      "One editor for web and mobile screens.",
      "Autogenerated Supabase schema and queries.",
      "Inline AI help for layout, copy, and code.",
    ],
  },
  {
    id: "team",
    label: "Product team",
    headline: "Design, build, and ship from one workspace.",
    bullets: [
      "Live collaboration with change history.",
      "GitHub integration for reviews and PRs.",
      "AI agents to generate flows and tests.",
    ],
  },
  {
    id: "agency",
    label: "Agency / Studio",
    headline: "Manage dozens of client apps from one cloud.",
    bullets: [
      "Dedicated workspaces per client.",
      "Token and cost controls per project.",
      "Template libraries you can reuse and resell.",
    ],
  },
];

const ideaCategories = [
  {
    id: "saas",
    label: "SaaS apps",
    ideas: [
      "Subscription dashboard for creators",
      "Analytics panel for small businesses",
      "Multi-tenant CRM for agencies",
    ],
  },
  {
    id: "social",
    label: "Communities",
    ideas: ["Learning community for developers", "Niche social network for artists", "Private members club platform"],
  },
  {
    id: "marketplace",
    label: "Marketplaces",
    ideas: ["Service marketplace for local jobs", "Digital asset marketplace", "Peer-to-peer rentals app"],
  },
];

const featureCards = [
  {
    title: "Smart UI Builder",
    description: "Generate beautiful layouts instantly with clean, production-ready code.",
  },
  {
    title: "Error-Aware Code Assist",
    description: "UR-DEV analyzes and fixes your code while keeping everything aligned.",
  },
  {
    title: "Scalable Projects",
    description: "Handle complex files and long projects without slowing down.",
  },
  {
    title: "Theme & Style Engine",
    description: "Create consistent themes, palettes, and animations for your projects.",
  },
];

const agentCards = [
  {
    title: "UI Agent",
    subtitle: "Layout and styling",
    description: "Takes your prompt and reshapes the page without breaking code.",
  },
  {
    title: "Schema Agent",
    subtitle: "Database design",
    description: "Designs tables, relationships, and migrations for Supabase.",
  },
  {
    title: "Deploy Agent",
    subtitle: "Shipping & checks",
    description: "Previews diffs, runs checks, and ships safely to production.",
  },
];

const galleryFilters = [
  { id: "featured", label: "Highlights" },
  { id: "discover", label: "Discover" },
  { id: "web", label: "Web apps" },
  { id: "mobile", label: "Mobile" },
  { id: "internal", label: "Internal tools" },
  { id: "prototype", label: "Prototypes" },
];

const galleryProjects = [
  {
    id: 1,
    title: "Studio launch workspace",
    category: "web",
    badge: "Website",
    authorInitial: "S",
    authorHandle: "studio-launch",
    remixCount: 123,
  },
  {
    id: 2,
    title: "Learning hub dashboard",
    category: "internal",
    badge: "Internal tool",
    authorInitial: "L",
    authorHandle: "learning-hub",
    remixCount: 88,
  },
  {
    id: 3,
    title: "Creator subscription page",
    category: "web",
    badge: "Website",
    authorInitial: "C",
    authorHandle: "creator-subscribe",
    remixCount: 204,
  },
  {
    id: 4,
    title: "City guide mobile app",
    category: "mobile",
    badge: "Mobile",
    authorInitial: "G",
    authorHandle: "guide-city",
    remixCount: 47,
  },
  {
    id: 5,
    title: "Task board for teams",
    category: "internal",
    badge: "Internal tool",
    authorInitial: "T",
    authorHandle: "team-board",
    remixCount: 156,
  },
  {
    id: 6,
    title: "Freelancer portfolio layout",
    category: "web",
    badge: "Website",
    authorInitial: "F",
    authorHandle: "freelance-portfolio",
    remixCount: 61,
  },
  {
    id: 7,
    title: "Bookings mobile flow",
    category: "mobile",
    badge: "Mobile",
    authorInitial: "B",
    authorHandle: "booking-flow",
    remixCount: 39,
  },
  {
    id: 8,
    title: "Finance overview prototype",
    category: "prototype",
    badge: "Prototype",
    authorInitial: "P",
    authorHandle: "proto-finance",
    remixCount: 12,
  },
];

const UrDevLandingPage: React.FC = () => {
  const [hasScrolled, setHasScrolled] = useState(false);
  const [promptMode, setPromptMode] = useState<"website" | "mobile" | "dashboard">("website");
  const [prompt, setPrompt] = useState("");
  const [promptStatus, setPromptStatus] = useState("Draft");
  const [activePersonaId, setActivePersonaId] = useState("solo");
  const [selectedIdeaCategoryId, setSelectedIdeaCategoryId] = useState("saas");
  const [activeGalleryFilter, setActiveGalleryFilter] = useState("featured");

  const activePersona = personas.find((p) => p.id === activePersonaId)!;
  const selectedCategory = ideaCategories.find((c) => c.id === selectedIdeaCategoryId)!;

  const visibleProjects = galleryProjects.filter((project) => {
    if (activeGalleryFilter === "featured") return true;
    if (activeGalleryFilter === "discover") return true;
    return project.category === activeGalleryFilter;
  });

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 8) {
        setHasScrolled(true);
      } else {
        setHasScrolled(false);
      }
    };

    handleScroll();
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const handleUseSamplePrompt = () => {
    if (promptMode === "website") {
      setPrompt("Create a landing page for a SaaS that helps teams design, build, and ship apps with AI.");
    } else if (promptMode === "mobile") {
      setPrompt("Design a mobile app with onboarding, home feed, and profile for a learning community.");
    } else {
      setPrompt("Generate an analytics dashboard with charts for active users, revenue, and errors.");
    }
    setPromptStatus("Ready to build");
  };

  const handleBuildClick = () => {
    if (!prompt.trim()) {
      handleUseSamplePrompt();
      return;
    }
    setPromptStatus("Analyzing prompt with AI agents");
    setTimeout(() => {
      setPromptStatus("Draft layout generated – open the IDE to refine.");
    }, 800);
  };

  const promptPlaceholder =
    promptMode === "website"
      ? "Describe the website you want to build with UR-DEV…"
      : promptMode === "mobile"
        ? "Describe the mobile app you want to build with UR-DEV…"
        : "Describe the dashboard or internal tool you want UR-DEV to assemble…";

  return (
    <div className="min-h-screen bg-[#020617] text-gray-100 flex flex-col">
      <header
        className={`sticky top-0 z-20 transition-colors ${
          hasScrolled
            ? "border-b border-white/10 bg-black/80 backdrop-blur"
            : "border-b border-transparent bg-transparent"
        }`}
      >
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-500/20 border border-cyan-400/60 text-xs font-semibold text-cyan-200">
              UR
            </div>
            <div>
              <div className="text-sm font-semibold tracking-tight">UR-DEV</div>
              <div className="text-[10px] uppercase tracking-[0.18em] text-gray-500">YOU ARE THE DEVELOPER</div>
            </div>
          </div>
          <nav className="hidden gap-6 text-xs text-gray-300 sm:flex">
            <a href="#frames" className="hover:text-white">
              Builder
            </a>
            <a href="#ideas" className="hover:text-white">
              Ideas
            </a>
            <a href="#agents" className="hover:text-white">
              AI Agents
            </a>
            <a href="#features" className="hover:text-white">
              Features
            </a>
          </nav>
          <div className="flex items-center gap-2 text-xs">
            <a
              href="/login"
              className="rounded-full border border-white/20 bg-transparent px-3 py-1.5 text-gray-200 hover:border-cyan-400/80 hover:text-cyan-100"
            >
              Sign In
            </a>
            <a
              href="/register"
              className="rounded-full bg-cyan-500 px-4 py-1.5 text-[11px] font-semibold text-black shadow-[0_0_20px_rgba(34,211,238,0.6)] hover:bg-cyan-400"
            >
              Launch IDE
            </a>
          </div>
        </div>
      </header>

      <main className="flex-1">
        <section className="px-4 pt-10 pb-16 sm:px-6 lg:px-8">
          <div className="mx-auto flex max-w-5xl flex-col items-center text-center gap-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/40 bg-emerald-500/10 px-3 py-1 text-[11px] font-medium text-emerald-100">
              <span className="inline-block h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
              UR-DEV – Build web + mobile with real databases and AI agents
            </div>

            <div className="space-y-3">
              <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl lg:text-5xl">
                UR-DEV – Build web & mobile apps with
                <span className="bg-gradient-to-r from-cyan-300 via-sky-400 to-indigo-300 bg-clip-text text-transparent">
                  {" "}
                  real databases
                </span>{" "}
                and
                <span className="bg-gradient-to-r from-emerald-300 to-teal-400 bg-clip-text text-transparent">
                  {" "}
                  AI agents
                </span>
                .
              </h1>
              <p className="max-w-2xl text-sm text-gray-400 mx-auto">
                Visual editor for web and mobile screens, native Supabase & GitHub integration, plus AI agents that
                understand your schema, your files, and your deployments.
              </p>
            </div>

            <section className="w-full max-w-3xl">
              <div className="flex flex-wrap items-center justify-between gap-3 text-xs">
                <div className="inline-flex flex-wrap gap-2">
                  <button
                    type="button"
                    onClick={() => setPromptMode("website")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "website"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Create a website
                  </button>
                  <button
                    type="button"
                    onClick={() => setPromptMode("mobile")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "mobile"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Build a mobile app
                  </button>
                  <button
                    type="button"
                    onClick={() => setPromptMode("dashboard")}
                    className={`rounded-full px-3 py-1 border ${
                      promptMode === "dashboard"
                        ? "border-cyan-400/80 bg-cyan-500/15 text-cyan-100 shadow-[0_0_20px_rgba(8,145,178,0.7)]"
                        : "border-white/15 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    Design a dashboard
                  </button>
                </div>
                <div className="flex items-center gap-2 text-[11px] text-gray-500">
                  <span className="h-1 w-1 rounded-full bg-emerald-400" />
                  <span>{promptStatus}</span>
                </div>
              </div>
              <div className="mt-4 text-left w-full">
                <div className="relative rounded-3xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.35),_transparent_65%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.4),_transparent_70%)] p-[1px] shadow-[0_0_45px_rgba(15,23,42,0.9)]">
                  <div className="relative rounded-[22px] border border-white/12 bg-black/95 px-4 py-6 sm:px-5 sm:py-7">
                    <div className="flex items-center gap-3">
                      <input
                        type="text"
                        value={prompt}
                        onChange={(e) => {
                          setPrompt(e.target.value);
                          setPromptStatus("Draft");
                        }}
                        placeholder={promptPlaceholder}
                        className="flex-1 bg-transparent border-none outline-none text-sm text-gray-100 placeholder:text-gray-500"
                      />
                      <button
                        type="button"
                        onClick={handleBuildClick}
                        className="inline-flex items-center gap-2 rounded-full bg-sky-500 px-4 py-1.5 text-[11px] font-semibold text-black shadow-[0_0_26px_rgba(59,130,246,0.9)] hover:bg-sky-400"
                      >
                        <span>Build with UR-DEV</span>
                        <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-black/20 text-[10px]">
                          →
                        </span>
                      </button>
                    </div>
                    <div className="mt-3 flex flex-wrap items-center gap-2 text-[11px] text-gray-300">
                      <button className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-3 py-1 hover:border-cyan-400/80 hover:text-cyan-100">
                        <span className="text-xs">＋</span>
                        <span>Attach</span>
                      </button>
                      <button className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-3 py-1 hover:border-cyan-400/80 hover:text-cyan-100">
                        <span className="text-xs">🎨</span>
                        <span>Import from Figma</span>
                      </button>
                      <button className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-3 py-1 hover:border-cyan-400/80 hover:text-cyan-100">
                        <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                        <span>Public</span>
                      </button>
                      <button className="inline-flex items-center gap-1 rounded-full border border-white/15 bg-white/5 px-3 py-1 hover:border-cyan-400/80 hover:text-cyan-100">
                        <span className="text-[10px]">⚡</span>
                        <span>Supabase</span>
                      </button>
                    </div>
                  </div>
                </div>
                <div className="mt-2 text-[11px] text-gray-500">
                  UR-DEV turns your description into real pages with Supabase, GitHub, and AI agents wired from the
                  first draft.
                </div>
              </div>
            </section>

            <ul className="grid gap-2 text-sm sm:grid-cols-2 mt-4" id="features-bullets">
              <li className="flex items-start gap-2">
                <span className="mt-0.5 text-cyan-300">◆</span>
                <span>Visual editor for web and mobile layouts.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-0.5 text-cyan-300">◆</span>
                <span>Native Supabase & GitHub integration.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-0.5 text-cyan-300">◆</span>
                <span>Built-in AI agents for UI, schema, and code.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-0.5 text-cyan-300">◆</span>
                <span>Real database, full control over your data.</span>
              </li>
            </ul>

            <div className="flex flex-wrap items-center justify-center gap-3 pt-1">
              <a
                href="/register"
                className="rounded-full bg-cyan-500 px-5 py-2 text-sm font-semibold text-black shadow-[0_0_26px_rgba(34,211,238,0.7)] hover:bg-cyan-400"
              >
                Start Building
              </a>
              <a
                href="/login"
                className="rounded-full border border-white/20 bg-white/5 px-4 py-2 text-xs font-semibold text-gray-100 hover:border-cyan-400/80 hover:text-cyan-100"
              >
                Log In
              </a>
              <div className="text-[11px] text-gray-500">
                No credit card required · Cheaper than typical low-code AI builders
              </div>
            </div>
          </div>
        </section>

        <section id="frames" className="border-t border-white/5 px-4 py-12 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-6xl">
            <div className="rounded-[32px] border border-white/10 bg-gradient-to-b from-slate-900/80 to-black/95 p-5 sm:p-6 shadow-[0_0_60px_rgba(15,23,42,0.9)] space-y-6">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                <div>
                  <div className="text-[11px] uppercase tracking-[0.18em] text-gray-500">UR-DEV workspace</div>
                  <h2 className="mt-1 text-xl font-semibold text-white">Explore what the community is building</h2>
                  <p className="text-sm text-gray-400 max-w-xl">
                    Browse example workspaces across different types of projects. Each card represents something you
                    could assemble in your own editor.
                  </p>
                </div>
                <button className="self-start rounded-full border border-white/20 bg-white/5 px-4 py-1.5 text-[11px] text-gray-200 hover:border-cyan-400/80 hover:text-cyan-100">
                  View all workspaces
                </button>
              </div>

              <div className="flex flex-wrap items-center gap-2 text-xs">
                {galleryFilters.map((filter) => (
                  <button
                    key={filter.id}
                    type="button"
                    onClick={() => setActiveGalleryFilter(filter.id)}
                    className={`rounded-full border px-3 py-1 ${
                      activeGalleryFilter === filter.id
                        ? "border-cyan-400/80 bg-cyan-500/20 text-cyan-100"
                        : "border-white/20 bg-white/5 text-gray-300 hover:border-cyan-400/70 hover:text-cyan-100"
                    }`}
                  >
                    {filter.label}
                  </button>
                ))}
              </div>

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {visibleProjects.map((project) => (
                  <div
                    key={project.id}
                    className="group relative flex flex-col overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-slate-900 to-black p-3 text-[11px] text-gray-300 hover:border-cyan-400/70 hover:bg-slate-900/90 transition"
                  >
                    <div className="mb-2 aspect-[4/3] w-full overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.25),_transparent_55%),_radial-gradient(circle_at_bottom,_rgba(167,139,250,0.22),_transparent_55%)]" />
                    <div className="mt-2 flex-1">
                      <div className="flex items-center justify-between gap-2">
                        <h3 className="truncate text-[12px] font-semibold text-white">{project.title}</h3>
                        <span className="whitespace-nowrap rounded-full border border-white/15 bg-white/5 px-2 py-0.5 text-[10px] text-gray-300">
                          {project.badge}
                        </span>
                      </div>
                      <div className="mt-2 flex items-center justify-between text-[10px] text-gray-400">
                        <div className="flex items-center gap-2">
                          <div className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-semibold text-gray-100">
                            {project.authorInitial}
                          </div>
                          <span className="truncate max-w-[90px]">{project.authorHandle}</span>
                        </div>
                        <span>{project.remixCount} copies</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="ideas" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-6xl space-y-14">
            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-white sm:text-3xl">Build smarter, not harder</h2>
                <p className="text-sm text-gray-400 max-w-xl">
                  UR-DEV understands what you are trying to build and generates clean, stable code that fits your stack.
                  Spend your time on ideas instead of boilerplate.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Instant component layouts with sensible defaults and full styling.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Automatic checks that flag broken props, missing imports, and typos.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Refactor suggestions that keep your UI and codebase easy to grow.</span>
                  </li>
                </ul>
              </div>

              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(59,130,246,0.35),_transparent_60%)]">
                  <span className="text-3xl text-sky-200">{"<>"}</span>
                </div>
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center order-last lg:order-first">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(45,212,191,0.28),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.32),_transparent_60%)]">
                  <span className="text-3xl text-emerald-200">↗</span>
                </div>
              </div>

              <div className="space-y-4 order-first lg:order-last">
                <h3 className="text-2xl font-semibold text-white sm:text-3xl">Your workflow—accelerated</h3>
                <p className="text-sm text-gray-400 max-w-xl">
                  From first idea to production, UR-DEV keeps the same project connected: prompts, editor, database, and
                  deployments all stay in sync.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Real-time preview that mirrors what your users will see on web and mobile.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Git-backed history so every change can be reviewed, reverted, or replayed.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>One-click deploys that ship the exact build you tested in the editor.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section id="agents" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-6xl space-y-14">
            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-white sm:text-3xl">Stay in control</h2>
                <p className="text-sm text-gray-400 max-w-xl">
                  Every suggestion stays visible and reversible. UR-DEV highlights what is changing so you can approve,
                  tweak, or roll back with confidence.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Clear diff views for layout, code, and schema edits.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Undo and redo with full history across prompts and manual edits.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Safe mode that prevents destructive changes to production data.</span>
                  </li>
                </ul>
              </div>

              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(94,234,212,0.32),_transparent_60%)]">
                  <span className="text-3xl text-sky-200">🎛️</span>
                </div>
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center">
              <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900 to-black/90 p-6 shadow-[0_0_40px_rgba(15,23,42,0.9)] flex items-center justify-center order-last lg:order-first">
                <div className="flex h-40 w-full max-w-md items-center justify-center rounded-2xl bg-[radial-gradient(circle_at_top,_rgba(244,114,182,0.3),_transparent_60%),_radial-gradient(circle_at_bottom,_rgba(129,140,248,0.32),_transparent_60%)]">
                  <span className="text-3xl text-pink-200">🎨</span>
                </div>
              </div>

              <div className="space-y-4 order-first lg:order-last">
                <h3 className="text-2xl font-semibold text-white sm:text-3xl">Create your own design language</h3>
                <p className="text-sm text-gray-400 max-w-xl">
                  Define tokens once and reuse them everywhere. UR-DEV keeps your color, spacing, and component
                  decisions consistent across pages and platforms.
                </p>
                <ul className="space-y-2 text-sm text-gray-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Custom palettes for brand colors, typography, and elevation.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Reusable components for headers, forms, and interactive blocks.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1 h-4 w-4 rounded-full bg-cyan-500/20 text-[10px] flex items-center justify-center text-cyan-300">
                      ●
                    </span>
                    <span>Responsive rules that keep layouts balanced on desktop and mobile.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section id="features" className="px-4 py-16 sm:px-6 lg:px-8 border-t border-white/5">
          <div className="mx-auto max-w-4xl text-center space-y-4">
            <h2 className="text-2xl font-semibold text-white sm:text-3xl">Ready to start your next project?</h2>
            <p className="text-sm text-gray-400 max-w-xl mx-auto">
              Move from idea to running app in a single workspace. UR-DEV connects prompts, editor, database, and
              deployments so you can focus on shipping.
            </p>
            <div className="pt-2 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
              <a
                href="/register"
                className="rounded-full bg-sky-500 px-6 py-2 text-sm font-semibold text-black shadow-[0_0_26px_rgba(59,130,246,0.7)] hover:bg-sky-400"
              >
                Start Building Now
              </a>
              <span className="text-[11px] text-gray-500">
                Join early teams using UR-DEV for web and mobile workspaces.
              </span>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-white/10 bg-black/95 text-[11px] text-gray-500">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
          <div className="flex flex-col gap-8 md:flex-row md:justify-between">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-500/20 border border-cyan-400/60 text-xs font-semibold text-cyan-200">
                  UR
                </div>
                <span className="text-sm font-semibold text-gray-100">UR-DEV</span>
              </div>
              <p className="max-w-xs text-[11px] text-gray-500">
                A focused workspace for building web and mobile apps with real databases, GitHub, and AI agents.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-6 sm:grid-cols-4 text-[11px]">
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Product</div>
                <a href="#frames" className="block hover:text-cyan-200">
                  Builder
                </a>
                <a href="#agents" className="block hover:text-cyan-200">
                  AI agents
                </a>
                <a href="#ideas" className="block hover:text-cyan-200">
                  Workflows
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Resources</div>
                <a href="/docs" className="block hover:text-cyan-200">
                  Documentation
                </a>
                <a href="/templates" className="block hover:text-cyan-200">
                  Templates
                </a>
                <a href="/changelog" className="block hover:text-cyan-200">
                  Changelog
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Company</div>
                <a href="/about" className="block hover:text-cyan-200">
                  About
                </a>
                <a href="/blog" className="block hover:text-cyan-200">
                  Blog
                </a>
                <a href="/careers" className="block hover:text-cyan-200">
                  Careers
                </a>
              </div>
              <div className="space-y-2">
                <div className="text-gray-300 font-semibold">Legal</div>
                <a href="/terms" className="block hover:text-cyan-200">
                  Terms
                </a>
                <a href="/privacy" className="block hover:text-cyan-200">
                  Privacy
                </a>
                <a href="/security" className="block hover:text-cyan-200">
                  Security
                </a>
              </div>
            </div>
          </div>

          <div className="mt-6 flex flex-col items-start justify-between gap-3 border-t border-white/10 pt-4 sm:flex-row sm:items-center">
            <span>© {new Date().getFullYear()} UR-DEV. All rights reserved.</span>
            <div className="flex gap-4 text-[11px]">
              <a href="https://twitter.com" className="hover:text-cyan-200">
                Twitter
              </a>
              <a href="https://discord.com" className="hover:text-cyan-200">
                Discord
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default UrDevLandingPage;
