/**
 * Page Registry Manager
 * 
 * Manages the central registry of all pages in the application.
 * Automatically tracks pages and their paths for navigation and routing.
 * 
 * @module utils/navigation/pageRegistryManager
 */

export interface PageRegistryEntry {
  path: string;
  filePath: string;
  title?: string;
}

export interface PageRegistry {
  [path: string]: string;
}

/**
 * Generates the page registry file content
 * 
 * @param {PageRegistryEntry[]} pages - Array of page entries
 * @returns {string} Complete pageRegistry.ts file content
 */
export const generatePageRegistry = (pages: PageRegistryEntry[]): string => {
  const registryEntries = pages
    .map(page => `  '${page.path}': '${page.filePath}'`)
    .join(',\n');

  return `/**
 * Page Registry
 * 
 * Central registry of all pages in the application.
 * Auto-generated by UR-DEV AI builder.
 */

export const pages = {
${registryEntries}
};

export const getPagePath = (route: string): string | null => {
  return pages[route] || null;
};

export const getAllRoutes = (): string[] => {
  return Object.keys(pages);
};
`;
};

/**
 * Parses existing page registry to extract registered pages
 * 
 * @param {string} registryContent - Content of pageRegistry.ts
 * @returns {PageRegistryEntry[]} Array of registered pages
 */
export const parsePageRegistry = (registryContent: string): PageRegistryEntry[] => {
  const pages: PageRegistryEntry[] = [];
  
  // Match registry entries: '/path': 'file/path'
  const entryPattern = /'([^']+)':\s*'([^']+)'/g;
  let match;
  
  while ((match = entryPattern.exec(registryContent)) !== null) {
    pages.push({
      path: match[1],
      filePath: match[2],
    });
  }
  
  return pages;
};

/**
 * Adds a new page to the registry
 * 
 * @param {string} existingRegistry - Current registry content
 * @param {PageRegistryEntry} newPage - New page to add
 * @returns {string} Updated registry content
 */
export const addPageToRegistry = (
  existingRegistry: string,
  newPage: PageRegistryEntry
): string => {
  const existingPages = parsePageRegistry(existingRegistry);
  
  // Check if page already exists
  const pageExists = existingPages.some(p => p.path === newPage.path);
  if (pageExists) {
    console.log(`Page ${newPage.path} already registered`);
    return existingRegistry;
  }
  
  // Add new page
  existingPages.push(newPage);
  
  return generatePageRegistry(existingPages);
};

/**
 * Detects page path from file path
 * 
 * @param {string} filePath - File path (e.g., 'public/login.html', 'src/pages/Profile.tsx')
 * @returns {string} Route path (e.g., '/login', '/profile')
 */
export const detectPagePath = (filePath: string): string => {
  // Extract filename without extension
  const filename = filePath.split('/').pop()?.replace(/\.(html|tsx|jsx)$/, '') || '';
  
  // Convert to lowercase route
  const route = filename.toLowerCase();
  
  // Handle special cases
  if (route === 'home' || route === 'homepage' || route === 'index') {
    return '/';
  }
  
  return `/${route}`;
};
